# Generated by Django 3.1.14 on 2023-03-17 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20230316_1231'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kerkesat',
            new_name='Requestss',
        ),
    ]
