# Generated by Django 3.1.14 on 2023-03-17 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20230317_0554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kerkesat',
            old_name='emri',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='kerkesat',
            old_name='numri_tel',
            new_name='phone_number',
        ),
    ]
